// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLmNOJe0b90Lk6D78tyvsLQAxitSDksms',
    appId: '1:851611299599:web:c8e5e9af8771363eee187a',
    messagingSenderId: '851611299599',
    projectId: 'kanglei-tourist-home',
    authDomain: 'kanglei-tourist-home.firebaseapp.com',
    databaseURL: 'https://kanglei-tourist-home-default-rtdb.firebaseio.com',
    storageBucket: 'kanglei-tourist-home.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2bS7fxzS2YHQLP0MCKywTA7zdVUmGmwc',
    appId: '1:851611299599:android:b88b6ba4e3ac9360ee187a',
    messagingSenderId: '851611299599',
    projectId: 'kanglei-tourist-home',
    databaseURL: 'https://kanglei-tourist-home-default-rtdb.firebaseio.com',
    storageBucket: 'kanglei-tourist-home.appspot.com',
  );
}
